reference: A02381
full_title: Computational Environments and Toolchains
short_title: Computational Env & Toolchains
credits: 5
level: Intermediate
author: RFRISBY
history_comment: ''
school: Science and Computing
department: Science
cluster: IT
aim: This is a practical module that requires the student to build, configure and
  manage computer systems and environments necessary for modern technologies.
programmes:
- timetable: COMP-0580
  code: WD_KPHTE_B
  name: Bachelor of Science (Honours) in Physics for Modern Technology
  stage: 3
  semester: 5
  status: M
prerequisites: []
corequisites: []
indicative_content:
- 'Linux overview: OS fundamentals; distributions; commonly used applications & tools,
  shell scripting'
- 'Operating systems resources and virtualisation: file systems, virtual machines,
  hypervisors, resource and configuration management'
- 'Introduction to computational science: survey of various computational tools (e.g.
  Python-based) used in exploring and analysing data in physics'
- 'Networking services: IP addressing, DNS, DHCP, NAT'
- 'Security: encryption, authentication, public key infrastructure'
- 'Concepts and applications of parallel and distributed programs: process interaction
  using shared variables and message passing; parallel computing; development of correct
  programs; general problem solving techniques; scientific computing; distributed
  systems; programming on multiple processor machines'
learning_outcomes:
- Build, configure and manage secure network infrastructure services.
- Use the Unix/Linux terminal interface, such as for data retrieval, text file manipulation,
  and scripting.
- Use a variety of Web-based and other computational resources and applications for
  retrieving and analysing data from scientific repositories (Open Access Directory).
- Develop solutions to problems in the retrieval and analysis of scientific data using
  modern programming languages (such as Python).
- Construct a pipeline of different programs that automates collation, analysis, and
  reporting of data.
learning_and_teaching_methods:
- This module adopts a practical approach with weekly hands-on laboratories and simulation
  exercises. Extensive use will be made of virtualised environments and microcontroller
  hardware in the practical work.
- This module will delivered as two double lab-based sessions.
learning_modes:
- full_time: 12
  name: Lecture
  part_time: ''
- full_time: 36
  name: Lab
  part_time: ''
- full_time: 87
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: 1,2,3
  main: false
  name: Assignment
  weighting: 40
  due_weeks: []
  comment: ''
- learning_outcomes: 4,5
  main: false
  name: Assignment
  weighting: 60
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Very little knowledge and understanding of Computational Environments and
  Toolchains. Unable to carry out critical thinking or practical skills.'
- '40%-49%: Demonstrate a limited knowledge of Computational Environments and Toolchains.
  May have some problems with critical thinking and problem solving. Adequate practical
  skills.'
- '50%-59%: Demonstrate satisfactory general knowledge of the main issues within Computational
  Environments and Toolchains. Good practical skills.'
- '60%-69%: Demonstrate skilled and sound knowledge of the subject matter. Show ability
  to analyse and logically discuss in an effective way. Good critical thinking and
  a high level of competence and efficiency in theoretical and practical areas of
  this subject.'
- '70%-100%: All of the above to an excellent level. Demonstrate authoritative handling
  of material and ability to develop innovative solutions to problems that rise in
  the configuration and management of Computational environments.'
essential_material: []
supplementary_material:
- '"10 Simple Rules for the Care and Feeding of Scientific Data." http://arxiv.org/pdf/1401.2134v1.pdf'
- '"Best Practices for Scientific Computing." http://arxiv.org/abs/1210.0530'
- 'Blum, R. and C. Bresnahan. _Linux Command Line and Shell Scripting Bible_. 3rd
  ed. New York: Wiley, 2015.'
- 'Nemeth, E., G. Synder, T. Hein and B. Whaley. _UNIX and Linux System Administration
  Handbook_. 4th ed. New York: Prentice Hall, 2010.'
- 'Newman, M. _Computational Physics (with Python)_. New York: CreateSpace Independent
  Publishing Platform, 2012.'
requested_resources:
- 'COMPUTER LAB: BYOD Lab'
mlo_to_po: ''
track_changes: true
