reference: A06902
full_title: Communication Skills and Computer Applications
short_title: Comm Skills & Comp Application
credits: 5
level: Introductory
author: MCAHILL
history_comment: ''
school: Science and Computing
department: Science
cluster: IT
aim: This module will teach the student how to communicate effectively using written
  and oral media. Students will be shown how to find and reference reliable information
  from a variety of sources. The student will gain a competency in the Microsoft Windows
  operating environment, as well as a proficiency in file and data management. An
  introduction to the basic principles of word processing, spreadsheets and presentations
  will be given. Report writing and presentation skills will be acquired, such that
  the student can competently present material in a format acceptable for reports
  and presentations.
programmes:
- timetable: COMP-0578
  code: WD_SFORS_D
  name: Bachelor of Science in Forestry
  stage: 1
  semester: 1
  status: M
- timetable: COMP-0578
  code: WD_SHORT_D
  name: Bachelor of Science in Horticulture
  stage: 1
  semester: 1
  status: M
- timetable: COMP-0578
  code: WD_SHORT_DX
  name: Bachelor of Science in Horticulture
  stage: 1
  semester: 1
  status: M
prerequisites: []
corequisites: []
indicative_content:
- 'Research and referencing: introduction to the sourcing of information, plagiarism
  and correct referencing'
- 'Writing skills: planning, structuring and executing a piece of written communication,
  proof-reading skills, editing skills'
- 'Communication in teams: stages in team-building, composition of successful teams'
- 'Structure of formal meetings: role of secretary, role of chairperson, function
  of agenda, minutes, standing orders, motions'
- 'Oral presentations: identifying the audience, defining objectives, structuring
  a presentation'
- 'MS Windows environment: effective and efficient file management, privacy and security'
- 'Word processing: creating, editing, formatting, saving and printing documents;
  creating and editing tables, table of contents and manipulation of images in documents'
- 'Spreadsheets: creating, editing, formatting, saving and printing workbooks and
  worksheets; sorting data, using formulas, charts, filters and links'
- 'Presentations: creating, editing, formatting, saving and printing presentations;
  use of images, animations and transitions in presentations'
learning_outcomes:
- Identify information from reliable sources and use an appropriate referencing system
  to generate a bibliography.
- Reproduce letters, reports, minutes and memoranda using word processing software.
- Report information orally using presentation software.
- Explain data using spreadsheet software.
learning_and_teaching_methods:
- Lectures.
- IT practicals.
- Group work.
learning_modes:
- full_time: 48
  name: Practical
  part_time: ''
- full_time: 87
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: '4'
  main: false
  name: In-Class Assessment
  weighting: 30
  due_weeks: []
  comment: ''
- learning_outcomes: '3'
  main: false
  name: Presentation
  weighting: 20
  due_weeks: []
  comment: ''
- learning_outcomes: 1,2
  main: false
  name: Portfolio
  weighting: 50
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Poor presentation and/or poorly communicated and formatted assignments.'
- '40%-49%: Presentation adequate, communication and technology use adequate.'
- '50%-59%: Presentation of material is competent with clear ideas and logical structure,
  few if any grammatical and spelling errors. Competent display of IT skills.'
- '60%-69%: Presentation of material is logical and persuasive, indicates strong communication
  and technical skills.'
- '70%-100%: Excellent communication of material supported by use of correct conventions
  and excellent use of technology.'
essential_material:
- 'McClave, H. _Communications for Business._ . 4th. Dublin: Gill & McMillan Ltd,
  2008.'
supplementary_material:
- 'Kennedy, J.A. _Complete ECDL 5_. 2nd ed.. Dublin: Gill & Macmillan, 2011.'
requested_resources:
- 'Room Type: Computer Lab'
mlo_to_po: ''
track_changes: true
