reference: A07698
full_title: Environmental Education
short_title: Environmental Education
credits: 5
level: Advanced
author: UMCDERMOTT
history_comment: ''
school: Science and Computing
department: Science
cluster: Horticulture
aim: This module will provide students with the necessary skills to teach people about
  the natural environment using interactive, informal learning activities and materials.
  These people may be groups or individuals, school children, members of the public
  or other interested groups.
programmes:
- timetable: EDUC-0023
  code: WD_SBSHO_B
  name: Bachelor of Science (Honours) in Land Management (in Horticulture)
  stage: 1
  semester: 2
  status: M
prerequisites: []
corequisites: []
indicative_content:
- Identifying good guiding techniques, identifying audiences, tailoring delivery and
  content to groups and individuals
- Safety issues, hazard identification of any activity
- Interpretation methods and techniques
- Planning activities to meet targets, evaluating activities
learning_outcomes:
- Propose a range of activities to exploit and explain the natural environment.
- Select a range of materials suitable for use on a site for educational purposes.
- Evaluate an existing interpretative program.
- Propose an educational/interpretative program with associated evaluation methods,
  for a given group.
learning_and_teaching_methods:
- Lectures.
- Site visits.
- Problem-based scenarios.
learning_modes:
- full_time: 36
  name: Lecture
  part_time: ''
- full_time: 12
  name: Field Trips
  part_time: ''
- full_time: 87
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: '3'
  main: false
  name: Group Project
  weighting: 20
  due_weeks: []
  comment: ''
- learning_outcomes: 1,2,4
  main: false
  name: Project
  weighting: 80
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Cannot suggest appropriate activities to use, with specific groups, unable
  to evaluate activities, cannot develop new material, cannot plan activities.'
- '40%-49%: Can suggest some appropriate activities and can modify existing activities
  has poor evaluation skills but can recognise key issues with activities, has poor
  planning skills, has problems selecting appropriate evaluation method.'
- '50%-59%: Can suggest several activities, can develop new activities, has competent
  evaluation skills, has good planning skills, can suggest several basic evaluation
  methods.'
- '60%-69%: Can suggest a range of activities, can develop new activities, has good
  evaluation skills recognising subtleties of different approaches. Has good planning
  skills and can select appropriate evaluation methods.'
- 70%-100%:Can suggest a wide range of activities, can develop new activities, has
  excellent evaluation skills recognising subtleties of different approaches and has
  developed self critical awareness. Has good planning skills and can develop and
  select appropriate evaluation methods.
essential_material:
- 'Ham, S.H. _Interpretation-Making a Difference on Purpose_. US: Fulcrum, 2013.'
supplementary_material:
- 'Diamond, J. _Practical Evaluation Guide: Tools for Museums and Other Informal Educational
  Settings_. US: Altmira, 1999.'
- 'Ham, S.H. _Environmental Interpretation: A Practical Guide for People With Big
  Ideas and Small Budgets_. US: Fulcrum, 1992.'
- 'Serrell, B. _Exhibit Labels: An Interpretive Approach_. 2nd ed. Maryland , US:
  Rowman & Littlefield Publishers, 2015.'
requested_resources:
- 'Lecture Room: Loose Seated'
mlo_to_po: ''
track_changes: true
