reference: A11386
full_title: Photonics Applications
short_title: Photonics Applications
credits: 5
level: Advanced
author: JHOULIHAN
history_comment: ''
school: Science and Computing
department: Science
cluster: Mathematics and Physics
aim: This module introduces a variety of applications in photonics.
programmes:
- timetable: PHYI-0033
  code: WD_KPHTE_B
  name: Bachelor of Science (Honours) in Physics for Modern Technology
  stage: 4
  semester: 8
  status: M
prerequisites: []
corequisites: []
indicative_content:
- Einstein relations, optical feedback and threshold conditions, resonator modes
- 'Laser types: gas, solid-state, semiconductor, quantum well, vertical cavity, and
  parametric lasers'
- Frequency stabilisation, distributed feedback structures
- Mode locking, Q switching
- Optical waveguiding, propagation in optical fibres
- Dielectric waveguide, optical fibre waveguide, waveguide modes
- Fiber-optic communications and technology
- Optical fibre fabrication
- Attenuation and scattering mechanisms
- Dispersion, pulse spreading and bandwidth effects; dispersion compensation
- Optical sources and detection
- 'Light emitting diodes and laser diodes: structures and characteristics; modulation
  schemes'
- Photomultipliers, p-n, pin and avalanche photodiodes, quantum efficiency, response
  speed, bandwidth; noise issues
learning_outcomes:
- Interpret the theory underpinning advanced photonic devices.
- Design and evaluate a range of photonic systems used in communications and metrology.
- Design and test optical communications networks.
- Design and manage various photonic systems.
learning_and_teaching_methods:
- Lectures.
- Practicals.
learning_modes:
- full_time: 24
  name: Lecture
  part_time: ''
- full_time: 18
  name: Practical
  part_time: ''
- full_time: 93
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: 1,2
  main: true
  name: Final Written Examination
  weighting: 70
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 30
- learning_outcomes: 3,4
  main: false
  name: Practical
  weighting: 30
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Inability to understand the basic concepts encountered in this module.'
- '40%-49%: Ability to demonstrate a basic understanding of advanced concepts in physical
  optics and photonic devices.'
- '50%-59%: Ability to understand and explain advanced concepts in physical optics
  and photonic devices and describe some applications of photonic systems.'
- '60%-69%: All the above, and in addition, apply problem-solving techniques to problems
  in photonics. Describe some key optical applications of photonic systems used in
  communications and metrology.'
- '70%-100%: All previous to an excellent level. Demonstrates an ability to comprehensively
  discuss the course material and analyse and design a range of photonic systems.'
essential_material:
- 'Ghatak, A. and K. Thyagarajan. _Introduction to Fibre Optics_. Cambridge: Cambridge
  University Press, 1998.'
- 'Hecht, E. _Optics_. New York: Addison Wesley Longman, 2000.'
- 'Rosencher, E. and B. Vinter. _Optoelectronics_. Cambridge: Cambridge University
  Press, 2002.'
- 'Wilson, J. and J. Hawkes. _Optoelectronics_. London: Prentice-Hall, 1998.'
supplementary_material: []
requested_resources:
- 'SCIENCE LAB: Physics'
mlo_to_po: ''
track_changes: true
