reference: A11377
full_title: Network and System Security
short_title: Network and System Security
credits: 5
level: Advanced
author: JMCGIBNEY
history_comment: ''
school: Science and Computing
department: Computing and Mathematics
cluster: Forensics and Security
aim: The objective of this module is to equip students with the necessary skills to
  evaluate the security of systems and networks and implement appropriate solutions.
  Network security is covered at all layers of the TCP/IP protocol suite and system
  security is considered with respect to operating system, applications, virtualisation
  and cloud technologies.
programmes:
- timetable: COMP-0672
  code: WD_KACCM_B
  name: BSc (Hons) in Applied Computing
  stage: 4
  semester: 7
  status: E
- timetable: COMP-0651
  code: WD_KACMI_B
  name: BSc (Hons) in Applied Computing (International)
  stage: 4
  semester: 7
  status: M
- timetable: COMP-0672
  code: WD_KCMSC_B
  name: BSc (Hons) in Computer Science
  stage: 4
  semester: 7
  status: E
- timetable: COMP-0672
  code: WD_KCOFO_B
  name: Bachelor of Science (Honours) in Computer Forensics and Security
  stage: 4
  semester: 7
  status: M
- timetable: COMP-0672
  code: WD_KCOMP_B
  name: Bachelor of Science (Honours) in Applied Computing
  stage: 4
  semester: 7
  status: E
- timetable: COMP-0651
  code: WD_KINTE_B
  name: Bachelor of Science (Honours) in Information Technology
  stage: 4
  semester: 1
  status: M
- timetable: COMP-0672
  code: WD_KITMA_B
  name: BSc (Hons) in Information Technology Management
  stage: 1
  semester: 7
  status: M
prerequisites: []
corequisites: []
indicative_content:
- Auditing and assessment
- Communications & network security - link layer, network layer, transport layer
- Mobile & wireless security
- Cloud security
- Identity and access management
- Access control models; firewalls
- Malware and intrusion detection
learning_outcomes:
- Evaluate Internet and cloud security technologies.
- Evaluate a selection of leading Internet security protocols.
- Compare and describe the roles of firewalls, intrusion detection and malware protection.
- Develop security policies (for example firewall rules) for a given scenario.
- Deploy popular network security technologies (e.g. TLS in various configurations).
- Set up test systems and evaluate their security.
- Assess the challenges with securing wireless communications and the main solution
  approaches.
learning_and_teaching_methods:
- This module will be presented by a combination of lectures and practicals.
- The lectures will be used to introduce new topics and their related concepts.
- The practical element allows the student to put into practice the theoretical concepts
  covered in the lectures.
learning_modes:
- full_time: 24
  name: Lecture
  part_time: ''
- full_time: 24
  name: Practical
  part_time: ''
- full_time: 87
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: 4,5,6
  main: false
  name: Practical
  weighting: 50
  due_weeks: []
  comment: ''
- learning_outcomes: 1,2,3,4,7
  main: false
  name: Assessment
  weighting: 50
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Unable to describe key network and system security technologies. Unable to
  effectively use relevant tools.'
- '40%-49%: Can describe in detail key security threats and technologies. Can carry
  out basic configuration of technologies to implement security policies for access
  control, encryption and authentication.'
- '50%-59%: All of the above and in addition can reason about the various approaches
  to security and their benefits and limitations.'
- '60%-69%: In addition, be capable of discussing the relative merits of securing
  at all layers or just at one layer. Also, can competently make use of security tools
  and technologies and carry out effective penetration tests.'
- '70%-100%: All of the above to an excellent level. Be able to describe a variety
  of new developments in security. Demonstrate an understanding of some the trade-offs
  involved in providing security.'
essential_material:
- '"The SANS Institute." http://www.sans.org/'
supplementary_material:
- '"Computer Emergency Response Team." http://www.cert.org/'
- '"Security Focus." http://www.securityfocus.com/'
- 'Gollmann, D. _Computer Security_. 3rd ed. Chichester: Wiley, 2011.'
- 'Stallings, W. and L. Brown. _Computer Security: Principles and Practice_. 3rd ed.
  Harlow: Pearson, 2014.'
requested_resources:
- 'COMPUTER LAB: BYOD Lab'
mlo_to_po: ''
track_changes: true
