reference: A13401
full_title: Application Security
short_title: Application Security
credits: 5
level: Advanced
author: CLPOWER
history_comment: ''
school: Science and Computing
department: Computing and Mathematics
cluster: Forensics and Security
aim: This module equips the student with knowledge of security vulnerabilities of
  application software taking into account both web and native applications. Methods
  used to solve these vulnerabilities are investigated. Intrusion Detection/Prevention
  Systems and Malicious Software are also presented. Students will be given a grounding
  in the area of Secure Software Development. This module also explores issues pertinent
  to Incident Response and Recovery.
programmes:
- timetable: COMP-0612
  code: WD_KCOMP_D
  name: BSc in Applied Computing
  stage: 3
  semester: 6
  status: M
- timetable: COMP-0612
  code: WD_KCSDV_B
  name: Bachelor of Science (Honours) in Software Systems Development
  stage: 4
  semester: 2
  status: M
- timetable: COMP-0612
  code: WD_KDEVP_B
  name: BSc (Hons) in Software Systems Development
  stage: 4
  semester: 8
  status: E
- timetable: COMP-0612
  code: WD_KDEVP_BI
  name: BSc (Hons) in Software Engineering
  stage: 4
  semester: 7
  status: M
- timetable: COMP-0612
  code: WD_KINFT_D
  name: Bachelor of Science in Information Technology
  stage: 3
  semester: 6
  status: M
- timetable: COMP-0612
  code: WD_KSOFP_B
  name: BSc (Hons) in Software Systems Practice
  stage: 1
  semester: 2
  status: M
prerequisites: []
corequisites: []
indicative_content:
- Web application security
- Native application security (mobile apps, desktops apps etc.)
- Intrusion detection/prevention systems
- Malicious software
- Secure software engineering
- Incident response and recovery
learning_outcomes:
- Assess a variety of security issues, vulnerabilities and fixes that arise in applications
  and categorise them by using information from CERT, OWASP and other trusted services.
- Compare the capabilities and limitations of intrusion detection systems and intrusion
  prevention systems.
- Appraise different threats posed by various categories of malware and explain different
  techniques to defend against them.
- Justify the need for appropriate incident response and recovery measures.
- Assess how security can be integrated into the software development process.
- Formulate a variety of security attacks in a simulated environment.
learning_and_teaching_methods:
- This module will be presented by a combination of lectures and practicals.
- The lectures will be used to introduce new topics and their related concepts. The
  student will be encouraged to participate in class discussions and ask questions
  to support their learning process.
- The practical element allows the student to put into practice the theoretical concepts
  covered in the lectures.
learning_modes:
- full_time: 24
  name: Lecture
  part_time: 12
- full_time: 24
  name: Practical
  part_time: 12
- full_time: 87
  name: Independent Learning
  part_time: 111
assessment_methods:
- learning_outcomes: 1,2,3,4,5,6
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: '5'
  main: false
  name: Assignment
  weighting: 30
  due_weeks: []
  comment: ''
- learning_outcomes: '6'
  main: false
  name: Practical
  weighting: 40
  due_weeks: []
  comment: ''
- learning_outcomes: 1,2,3,4
  main: false
  name: In-Class Assessment
  weighting: 30
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Unable to describe typical security vulnerabilities of application software.
  Unable to explain the operation of IDS/IPS. Unable to describe the different categories
  of malware. Unable to describe how security can be incorporated into the software
  engineering process.'
- '40%-49%: Be able to describe typical security vulnerabilities of application software.
  Be able to explain the operation of IDS/IPS. Be able to describe the different categories
  of malware. Be able to describe how security can be incorporated into the software
  engineering process. Be able to explain the need for appropriate incident response
  and recovery.'
- '50%-59%: All of the above and the ability to discover and review contemporary knowledge
  of application software vulnerabilities, secure software development techniques,
  IDS/IPS, malicious software and incident response and recovery techniques.'
- '60%-69%: All of the above and be able to solve problems within application software
  security by experimenting with the appropriate skills and tools.'
- '70%-100%: All the above to an excellent level and the ability to analyse and design
  application software security solutions to a high standard for a range of security
  threats through the use and modification of appropriate skills and tools.'
essential_material:
- '"Open Web Application Security Project (OWASP)." https://www.owasp.org'
supplementary_material:
- '"Computer Emergency Response Team, CERT." http://www.cert.org'
- '"Security Focus." http://www.securityfocus.com/'
- '"The SANS Institute." http://www.sans.org'
- 'Stallings, W. _Cryptography and Network Security, Principles and Practice_. 6th
  ed. England: Pearson, 2014.'
- 'Stallings, W. _Network Security Essentials_. England: Pearson, 2014.'
requested_resources:
- 'COMPUTER LAB: BYOD Lab'
mlo_to_po: ''
track_changes: true
