reference: A13802
full_title: Cloud Infrastructure and Security
short_title: Cloud Infrastruct and Security
credits: 10
level: Postgraduate
author: RFRISBY
history_comment: ''
school: Science and Computing
department: Computing and Mathematics
cluster: Networks and Cloud
aim: This module will build on the student?s prior knowledge of computer networks
  and security to provide the student with a thorough understanding of many of the
  latest infrastructure technologies and services. The main areas covered in this
  module are IP networking, network monitoring and network automation as well as the
  security of systems, networks and modern distributed applications.
programmes: []
prerequisites: []
corequisites: []
indicative_content:
- In depth treatment (assuming prior knowledge) of IP networking; addressing
- Routing & switching technologies
- Network monitoring & performance
- Software defined networking
- Infrastructure as Code
- 'Security fundamentals: cryptographic techniques for confidentiality, authentication
  and integrity; key management and digital certificates'
- 'Network & system security: protocols and technologies'
- 'Security assessment: black and white box testing; penetration testing; standards
  compliance'
- Secure software development
learning_outcomes:
- Evaluate how the latest technologies in networking and security (protocols, architectures)
  operate and how they can be deployed.
- Compare and contrast major networking technologies found on the Internet today and
  assess their suitability for different scenarios and user requirements.
- Design and implement solutions for application infrastructure automation.
- Evaluate network performance using appropriate monitoring tools.
- Assess the key aspects of system and network security in a heterogeneous environment.
- Carry out a security assessment on a running application.
- Implement a selection of secure software development best practices.
learning_and_teaching_methods:
- Combination of lectures and computer-based practical and simulation exercises.
- The practical component will be delivered in one double lab session.
- Self-directed learning.
learning_modes:
- full_time: 24
  name: Lecture
  part_time: 24
- full_time: 24
  name: Lab
  part_time: 24
- full_time: 222
  name: Independent Learning
  part_time: 222
assessment_methods:
- learning_outcomes: 1,2,3,4,5,7
  main: true
  name: Final Written Examination
  weighting: 50
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 50
- learning_outcomes: 1,2,3,4,5
  main: false
  name: Assignment
  weighting: 30
  due_weeks: []
  comment: ''
- learning_outcomes: 3,4,6,7
  main: false
  name: Lab Report
  weighting: 20
  due_weeks: []
  comment: ''
assessment_criteria:
- '<40%: Unable to interpret and describe key concepts of the specific knowledge domains
  of networking, security and emerging technologies in these areas.'
- '40%-59%: Able to interpret, describe and discuss key concepts of the specific knowledge
  domains of networking, security and emerging technologies in these areas. Able to
  discover and integrate related knowledge into application architectures.'
- '60%-69%: Able to solve problems within the specific knowledge domains by experimenting
  with the appropriate skills and tools.'
- '70%-100%: All the above to an excellent level. Be able to analyse and design solutions
  to a high standard for a range of both complex and unforeseen problems through the
  use and modification of appropriate skills and tools.'
essential_material:
- '"Open Web Application Security Project (OWASP)." https://www.owasp.org/'
- '"The SANS Institute." https://www.sans.org/'
supplementary_material:
- 'Kurose, J.F. and K.W. Ross. _Computer Networking: A Top-down Approach_. 6th. New
  York: Pearson, 2012.'
- 'McGraw, G. _Software Security: Building Security In_. Boston: Addison-Wesley, 2006.'
- 'Stallings, W. _Cryptography and Network Security: Principles and Practice_. 6th
  ed. London: Pearson, 2013.'
- 'Stallings, W. _Foundations of Modern Networks: SDN, NFV, QoE, IoT, and Cloud_.
  1st. New York: Pearson, 2016.'
requested_resources:
- 'COMPUTER LAB: BYOD Lab'
mlo_to_po: ''
track_changes: true
