reference: A18281
full_title: Theory and Application of Transformers and Line Reactors
short_title: Transformer & Reactor Theory
credits: 5
level: Advanced
author: NEMURPHY
history_comment: ''
school: Science and Computing
department: Engineering Technology
cluster: Engineering
aim: The aim of this module is to provide the student with a professional level of
  understanding, and the ability to apply associative design and calculation methods
  to the areas of MV and HV power transformers and line reactors on transmission and
  distribution power networks. In addition, the student will gain proficiency in the
  areas of safety procedures, and maintenance requirements of transformers and reactors.
programmes:
- timetable: ''
  code: WD_ETRIC_B
  name: Bachelor of Engineering (Honours)
  stage: 4
  semester: 7
  status: M
- timetable: ''
  code: WD_ETRIC_B
  name: Bachelor of Engineering (Honours) in Electrical Engineering
  stage: 4
  semester: 7
  status: M
- timetable: ''
  code: WD_ETRIC_BI
  name: BEng (Hons) in Electrical and Automation Engineering (International)
  stage: 4
  semester: 7
  status: M
prerequisites: []
corequisites: []
indicative_content:
- Classification of transformers and line reactors
- Phase shift transformer theory & applications of tertiary windings
- Shunt/series, capacitive, and inductive reactor rating & design.
- Onload & offload transformer/reactor tap-changing methods and applications
- Core assembly, winding practices, insulation types, and cooling methods.
- Current inrush, over-voltage, and short-circuit protection.
- CELNEC, IEEE/ANSI, and IEC Standardisation of transformers and reactors.
- Transformer/reactor loss capitalisation, and optimum design criteria
learning_outcomes:
- Evaluate and understand the design and operation of power transformers and reactors
  on HV and MV sectors of a national electrical grid.
- Configure the tertiary winding of a transformer for phase shift, and load balancing
  applications.
- Determine appropriate tap changer designs for both on-load and off-load configurations.
- Demonstrate proficiency in the methods of core assembly, winding practice, insulation
  type, and cooling methods of inductor hardware.
- Apply theoretical background to the detection and suppression of current inrush
  and other parameters that exceed inductor rating.
- Generate costing for optimum design criteria and capitalisation of inductor loss.
- Provide confirmation of compliance with CELNEC, IEEE/ANSI, and IEC Standardisation
  in terms of operation and safety.
learning_and_teaching_methods:
- The module delivery method will consist of lectures, laboratories, mini-project,
  and formative assessments.
- The emphasis on module delivery is to engage the student in the learning of the
  module content through the integration of course materials with case studies in
  laboratories and the application within a mini-project.
- The formative assignments will provide an opportunity for the student to engage
  with the material as it is being applied to maximise the learning opportunities
  of the student.
- Self-directed learning, moodle, and recommended software applications optimise the
  delivery of module material in specific areas where additional processes are required.
learning_modes:
- full_time: 36
  name: Lecture
  part_time: ''
- full_time: 12
  name: Practical
  part_time: ''
- full_time: 87
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: 1,2,3,4,5
  main: true
  name: Final Written Examination
  weighting: 70
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 30
- learning_outcomes: 2,6,7
  main: false
  name: Project
  weighting: 10
  due_weeks: []
  comment: ''
- learning_outcomes: 6,7
  main: false
  name: Practical
  weighting: 10
  due_weeks: []
  comment: ''
- learning_outcomes: 3,6,7
  main: false
  name: Case Studies
  weighting: 10
  due_weeks: []
  comment: ''
assessment_criteria:
- '70% - 100%: The learner has: attained the module learning outcomes at an excellent
  level; demonstrated a comprehensive knowledge of the associated subject matter;
  achieved an excellent level of the skills required for the subject matter; demonstrated
  the ability to carry out further investigation and problem solving associated with
  the subject matter.'
- '60% - 69%: The learner has: attained the module learning outcomes at a very good
  level; demonstrated a detailed knowledge of the associated subject matter; achieved
  a very good level of the skills required for the subject matter.'
- '50% - 59%: The learner has: attained the module learning outcomes at a good level;
  demonstrated a good knowledge of the associated subject matter; achieved a good
  level of the skills required for the subject matter.'
- '40% - 49%: The learner has: attained the module learning outcomes at a basic level;
  demonstrated a basic knowledge of the associated subject matter; achieved a basic
  level of the skills required for the subject matter.'
- '<40%: The learner has not: attained the module learning outcomes; demonstrated
  sufficient knowledge of the associated subject matter; demonstrated a sufficient
  level of the skills required for the subject matter.'
essential_material:
- 'Harlow, J.H. _Electrical Power Transformer Engineering_. 3rd ed. US: CRC Press,
  May 2012.'
supplementary_material:
- 'Das, J.C. _Transients in Electrical Systems: Analysis, Recognition, and Mitigation_.
  1st. US: McGraw-Hill, 2010.'
- 'Del Vecchio, R.M., B. Poulin, P. Feghali, M.S. Dilipkumar and A. Rajendra. _Transformer
  Design Principles: With Applications to Core-Form Power Transformers_. 2nd ed. US:
  CRC Press, May 2010.'
requested_resources: []
mlo_to_po: ''
track_changes: true
