reference: A35619
full_title: Programming with Applications in Electronic Engineering - NUIST
short_title: Programming with Applications (NUIST)
credits: 5
level: Postgraduate
author: CLAIRE.FITZPATRICK
history_comment: ''
school: Science and Computing
department: Engineering Technology
cluster: Software and Information Systems
aim: The aim of this module is to highlight the computational approach to solving
  electrical engineering problems. The concepts and techniques covered in this module
  will be applicable in projects or problem-solving work that contain a strong computational
  with particular emphasis on numerical methods for computation. The module is designed
  such that a significant fraction of the student's time is spent programming/solving
  specific engineering problems, rather than learning abstract techniques.
programmes:
- timetable: MSTU-0001
  code: WD_EELEN_G
  name: Postgraduate Diploma in Engineering in Electronic Engineering
  stage: 1
  semester: 1
  status: E
- timetable: MSTU-0001
  code: WD_EELEN_R
  name: Master of Engineering in Electronic Engineering
  stage: 1
  semester: 1
  status: E
- timetable: ''
  code: WD_EELEN_RI
  name: MEng in Electronic Information Systems
  stage: 1
  semester: 2
  status: E
prerequisites: []
corequisites: []
indicative_content:
- 'Introduction to scientific programming: floating point numbers and error analysis,
  machine precision, general classification of computational problems, procedural
  programming constructs such as sequential, conditional and looping constructs.'
- 'Overview of computational problems: integration and differentiation, interpolation
  and extrapolation, ordinary differential equations, partial differential equations,
  matrix methods, curve fitting, Monte Carlo other simulation methods'
- 'Scientific programming tools: Matlab (or equivalent language such as Octave or
  Scilab), Python (or an equivalent language, such as Julia or Java ), LaTeX, Markdown,
  etc.'
- 'Programming applications: Periodigrams, windowing function, code implementation
  of digital signals, convolution -- FIR filters, signal sequences, time varying FT
  (STFT), and wavelets.'
learning_outcomes:
- Utilise the procedural programming paradigm for problems in electronic engineering,
  such as code implementation of digital signals, periodigrams etc.
- Design algorithms and programs using pseuduocode and flowcharts.
- Demonstrate proficiency with linear algebra within Matlab(or similar language).
- Explore aspects of statistics and probability such pseudorandom number generators,
  simple stochastic models and inclusion of noise.
- Utilise essential methods and techniques (error analysis, problem classification)
  for symbolic/numerical computation in engineering.
learning_and_teaching_methods:
- The module is covered through a series of practical problem solving sessions and
  directed independent learning.
- Due to the very practical nature of the skills to be acquired in this module, these
  practical sessions will be centred around the idea of learning by doing, whereby
  students develop proficiency in the specified skill set through guided activities,
  and whereby lecturers provide short formal presentations of relevant concepts and
  technologies, as well as practical tips, feedback, and advice on best practices.
- Active engagement with frequent practice on examples is strongly encouraged through
  regular course work consisting of a mixture of practical activities graded from
  guided to self-directed tasks.
learning_modes:
- full_time: 36
  name: Practical
  part_time: ''
- full_time: 99
  name: Independent Learning
  part_time: ''
assessment_methods:
- learning_outcomes: ''
  main: true
  name: Continuous Assessment
  weighting: 100
- learning_outcomes: 1,2
  main: false
  name: Assignment
  weighting: 25
  due_weeks: []
  comment: ''
- learning_outcomes: '3'
  main: false
  name: Assignment
  weighting: 25
  due_weeks: []
  comment: ''
- learning_outcomes: 4,5
  main: false
  name: Practical
  weighting: 50
  due_weeks: []
  comment: ''
assessment_criteria:
- '70% - 100%: The learner has: attained the module learning outcomes at an excellent
  level; demonstrated a comprehensive knowledge of the associated subject; achieved
  an excellent level of the skills required for the subject matter; demonstrated the
  ability to carry out further investigation and problem solving associated with the
  subject matter.'
- '60% - 69%: The learner has: attained the module learning outcomes at a very good
  level; demonstrated a detailed knowledge of the associated subject matter; achieved
  a very good level of the skills required for the subject matter.'
- '40% - 59%: The learner has: attained the module learning outcomes at a good level;
  demonstrated a good knowledge of the associated subject matter; achieved a good
  level of the skills required for the subject matter.'
- '<40%: The learner has not: attained the module learning outcomes; demonstrated
  sufficient knowledge of the associated subject matter; demonstrated a sufficient
  level of the skills required for the subject matter.'
essential_material: []
supplementary_material:
- 'Rauscher, C., V. Janssen and R. Minihold. _Fundamentals of Spectrum Analysis_.
  Berlin: Rohde & Schwarz GmbH, 2007.'
- "Siauw, T. and A. Bayen. _An Introduction to MATLAB\xAE Programming and Numerical\
  \ Methods for Engineers_. London: Academic Press, 2014."
- 'Taylor, F.J. and J. Mellot. _Hands-On Digital Signal Processing_. Canada: McGraw-Hill
  Professional Publishing, 1998.'
requested_resources:
- 'Room Type: Computer Lab'
mlo_to_po: ''
track_changes: true
